version: "3.9"
services:
  db:
    image: bitnami/postgresql:14.1.0
    ports:
      - '5433:5432'
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 123123123
      POSTGRESQL_DATABASE: gshop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: bitnami/redis:6.2.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  migrate:
    build:
      context: ./backend
      dockerfile: ./cmd/migrate/Dockerfile
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: 123123123
      POSTGRES_DATABASE: gshop
      POSTGRES_SSLMODE: disable
    depends_on:
      db:
        condition: service_healthy
  server:
    build:
      context: ./backend
      dockerfile: ./cmd/server/Dockerfile
    environment:
      APP_ENV: dev
      LOG_LEVEL: DEBUG
      HTTP_PORT: 3000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: 123123123
      POSTGRES_DATABASE: gshop
      POSTGRES_SSLMODE: disable
      REDIS_HOST: redis:6379
      REDIS_DB: 0
      TOKEN_TTL: 86400
      SIGNING_KEY: randomestring
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
  nginx:
    build: nginx
    ports:
      - 18080:80
    depends_on:
      - server
      - frontend
