name: ci-build

on:
  push:
    branches: [master]
    paths:
      - backend/**
  pull_request:
    branches: [master]
    paths:
      - backend/**
    types: [closed]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - name: Pull dependencies
        working-directory: ./backend
        run: go mod download

      - name: Build
        working-directory: ./backend
        run: go build
