name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1 # Build with Dockerfile
        with:
          github_token: ${{ secrets.REVIEW_DOG_TOKEN }}

  golint:
    name: runner / golint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.REVIEW_DOG_TOKEN }}
          golangci_lint_flags: '--disable-all -E golint'
          tool_name: golint # Change reporter name.
          level:
            warning # GitHub Status Check won't become failure
            # with this level.
