name: reviewdog
on: [pull_request]
jobs:
  golint:
    name: runner / golint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEW_DOG_TOKEN }}
          golangci_lint_flags: '--enable-all --exclude-use-default=false'
